party:
  players:
  - player_id: p1
    display_name: Agent 1
    score: 0
  - player_id: p2
    display_name: Agent 2
    score: 0
  - player_id: p3
    display_name: Agent 3
    score: 0
  - player_id: p4
    display_name: Agent 4
    score: 0
  - player_id: p5
    display_name: Agent 5
    score: 0
  - player_id: p6
    display_name: Agent 6
    score: 0
  - player_id: p7
    display_name: Agent 7
    score: 0
  - player_id: p8
    display_name: Agent 8
    score: 0
